name: 'Visual Regression Testing'

description: 'Run visual regression testing'

inputs:
  aws-access-key-id:
    description: 'AWS access key id'
    required: true
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: true
  working-directory:
    description: 'Working directory'
    required: false
    default: '.'

runs:
  using: 'composite'

  steps:
    - name: Check if VRT enabled
      id: vrt_enabled
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        vrtClientId=`echo $(jq -r '.plugins."reg-notify-github-plugin".clientId' <<< "$(cat regconfig.json)")`
        if [[ $vrtClientId != "" ]]; then
          echo "runVrt=true" >> $GITHUB_OUTPUT
          echo "VRT Enabled"
        else
          echo "VRT Not enabled"
        fi

    - name: Install Chrome
      if: steps.vrt_enabled.outputs.runVrt
      id: chrome
      uses: browser-actions/setup-chrome@facf10a55b9caf92e0cc749b4f82bf8220989148 # v1.7.2
      with:
        chrome-version: 127

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: yarn install --frozen-lockfile

    - name: Build storybook
      if: steps.vrt_enabled.outputs.runVrt
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: yarn storybook:build

    - name: create the current snapshot
      if: steps.vrt_enabled.outputs.runVrt
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: yarn storycap --chromiumPath ${{ steps.chrome.outputs.chrome-path }}

    - name: Run Reg-suit (pull request)
      if: steps.vrt_enabled.outputs.runVrt && github.event_name == 'pull_request'
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      working-directory: ${{ inputs.working-directory }}
      run: yarn run reg-suit run

    - name: Run Reg-suit (push)
      if: steps.vrt_enabled.outputs.runVrt && github.event_name == 'push'
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        WORKING_DIRECTORY: ${{ inputs.working-directory }}
      working-directory: ${{ inputs.working-directory }}
      run: |
        node ${{ github.action_path }}/generate-reg-config.js "${{ github.workspace }}"
        yarn run reg-suit run --config=regconfig-push.json
